version: '3.0'

expectations:
  population_size: 1000

actions:

  # Generate ethnicity study population
  generate_study_population_ethnicity:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_ethnicity 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity*.csv

  # Hypertension Register (Indicator HYP001)
  generate_study_population_hyp001:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_hyp001 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_hyp001*.csv
  
  join_ethnicity_hyp:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_hyp*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_hyp001]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_hyp*.csv

  generate_measures_hyp001:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_hyp001 
       --output-dir=output/joined
     needs: [join_ethnicity_hyp]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_hyp001_*_rate.csv
  
  # Learning Disability (Indicator LD004)
  generate_study_population_ld004:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_ld004 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ld004*.csv
  
  join_ethnicity_ld:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_ld*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_ld004]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_ld*.csv

  generate_measures_ld004:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_ld004 
       --output-dir=output/joined
     needs: [join_ethnicity_ld]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_ld004_*_rate.csv

  # Palliative care (Indicator PC001)
  generate_study_population_pc001:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_pc001 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_pc001*.csv
  
  join_ethnicity_pc:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_pc*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_pc001]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_pc*.csv

  generate_measures_pc001:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_pc001 
       --output-dir=output/joined
     needs: [join_ethnicity_pc]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_pc001_*_rate.csv

  # Stroke and transient ischaemic attack (Indicator STIA001)
  generate_study_population_stia001:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_stia001 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_stia001*.csv
  
  join_ethnicity_stia:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_stia*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_stia001]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_stia*.csv

  generate_measures_stia001:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_stia001 
       --output-dir=output/joined
     needs: [join_ethnicity_stia]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_stia001_*_rate.csv

# Asthma register (ast_reg)
  generate_study_population_ast_reg:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_ast_reg 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ast_reg*.csv
  
  join_ethnicity_ast_reg:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_ast*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_ast_reg]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_ast*.csv

  generate_measures_ast_reg:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_ast_reg 
       --output-dir=output/joined
     needs: [join_ethnicity_ast_reg]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_ast_reg_*_rate.csv

# Diabetes register (dm_reg)
  generate_study_population_dm_reg:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_dm_reg 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_dm_reg*.csv     


  # ZZ EXAMPLE REGISTER FOR TESTING
  # TODO: TO BE DELETED LATER
  generate_study_population_yy_001:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_yy_001 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_yy_001*.csv
  
  # ZZ EXAMPLE REGISTER FOR TESTING
  # TODO: TO BE DELETED LATER
  generate_study_population_zz_001:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_zz_001 
      --index-date-range "2021-04-01 to 2022-03-01 by month"
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_zz_001*.csv
  
  # Generate decile charts
  # TODO: Currently commented out because returning errors
  # generate_deciles_charts:
  #   run: >
  #     deciles-charts:v0.0.1
  #     --input_dir output/joined
  #     --output_dir output/joined
  #   needs: [generate_measures_hyp001, generate_measures_ld004, generate_measures_pc001]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/joined/deciles_chart_*.png
