version: '3.0'

expectations:
  population_size: 1000

actions:

  # Generate ethnicity study population
  generate_study_population_ethnicity:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_ethnicity 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ethnicity*.csv

  # Hypertension Register
  generate_study_population_hyp_reg:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_hyp_reg 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_hyp_reg*.csv
  
  join_ethnicity_hyp:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_hyp*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_hyp_reg]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_hyp*.csv

  generate_measures_hyp_reg:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_hyp_reg 
       --output-dir=output/joined
     needs: [join_ethnicity_hyp]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_hyp_reg_*_rate.csv
  
  # Learning Disability
  generate_study_population_ld_reg:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_ld_reg 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_ld_reg*.csv
  
  join_ethnicity_ld:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_ld*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_ld_reg]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_ld*.csv

  generate_measures_ld_reg:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_ld_reg 
       --output-dir=output/joined
     needs: [join_ethnicity_ld]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_ld_reg_*_rate.csv

  # Palliative care
  generate_study_population_pc_reg:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_pc_reg 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_pc_reg*.csv
  
  join_ethnicity_pc:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_pc*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_pc_reg]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_pc*.csv

  generate_measures_pc_reg:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_pc_reg 
       --output-dir=output/joined
     needs: [join_ethnicity_pc]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_pc_reg_*_rate.csv

  # Stroke and transient ischaemic attack
  generate_study_population_stia001:
    run: > 
      cohortextractor:latest generate_cohort 
      --study-definition study_definition_stia001 
      --index-date-range "2021-04-01 to 2022-03-01 by month" 
      --output-dir=output
      --output-format=csv
    outputs:
      highly_sensitive:
        cohort: output/input_stia001*.csv
  
  join_ethnicity_stia:
    run: >
      cohort-joiner:v0.0.12 
        --lhs output/input_stia*.csv
        --rhs output/input_ethnicity*.csv
        --output-dir output/joined
    needs: [generate_study_population_ethnicity, generate_study_population_stia001]
    outputs:
      highly_sensitive:
        cohort: output/joined/input_stia*.csv

  generate_measures_stia001:
     run: >
       cohortextractor:latest generate_measures 
       --study-definition study_definition_stia001 
       --output-dir=output/joined
     needs: [join_ethnicity_stia]
     outputs:
       moderately_sensitive:
         measure_csv: output/joined/measure_stia001_*_rate.csv
  
  # Generate decile charts
  # TODO: Currently commented out because returning errors
  # generate_deciles_charts:
  #   run: >
  #     deciles-charts:v0.0.1
  #     --input_dir output/joined
  #     --output_dir output/joined
  #   needs: [generate_measures_hyp_reg, generate_measures_ld_reg, generate_measures_pc_reg]
  #   outputs:
  #     moderately_sensitive:
  #       cohort: output/joined/deciles_chart_*.png
